version: 2
experimental:
  pipelines: true
jobs:
  build:
    working_directory: ~/slickgrid-universal
    docker:
      - image: circleci/node:13-browsers
    steps:
      - checkout
      - restore_cache:
          key: slickgrid-universal-build-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: slickgrid-universal-build-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: TypeScript Build (tsc)
          command: yarn run build
      - run:
          name: Run Jest tests with JUnit as reporter
          command: ./node_modules/.bin/jest --config test/jest.config.js --ci --runInBand --collectCoverage=true --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - run:
          name: Upload Jest coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Build Full Bundle (all Bundler types)
          command: yarn run bundle
      # - run:
      #     name: Website Prod Build
      #     command: yarn run build:demo
      - run:
          name: Run Web Server
          command:  npm run dev:watch
          background: true
      # - run:
      #     name: Run Web Server
      #     command: npm run serve
      #     background: true
      - run:
          name: Running Cypress E2E tests with JUnit XML reporter
          command: |
            yarn run cypress:ci

