name: ðŸ·ï¸ Release to NPM

on:
  workflow_dispatch:
    inputs:
      dryrun:
        type: boolean
        description: Dry-Run
      tag:
        type: choice
        default: latest
        description: NPM tag (defaults to 'latest')
        options:
          - latest
          - alpha
          - beta
          - next

permissions:
  contents: write # to be able to publish a GitHub release
  id-token: write # to enable use of OIDC for npm provenance
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests

jobs:
  deploy-npm-latest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Retrieve current Date Time in EST
        shell: bash
        run: echo "START_TIME=$(TZ=":America/New_York" date -R|sed 's/.....$//')" >> $GITHUB_ENV

      - name: Current datetime - ${{ env.START_TIME }}
        run: echo ${{ env.START_TIME }}

      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ github.event.pull_request.merged != true && contains('["ghiscoding"]', github.actor) != true }}
        name: Exit early when current actor is not allowed to push new release
        run: |
          echo "Error: Your GitHub username (${{ github.actor }}) is not on the allowed list of Admins that can run this workflow"
          exit 1

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false

      - name: Set NodeJS
        uses: actions/setup-node@v6
        with:
          registry-url: 'https://registry.npmjs.org/'
          node-version: 24

      - run: node --version
      - run: npm --version

      - name: Run pnpm install dependencies
        run: pnpm install

      - name: Build Everything
        run: pnpm build

      - name: Lerna Version (build query)
        shell: bash
        run: |
          if ${{inputs.dryrun == true && (inputs.tag == 'alpha' || inputs.tag == 'beta' || inputs.tag == 'next')}}
          then
              echo "LERNA_VERSION_TYPE=ðŸ§ª Dry-Run w/Prerelease" >> $GITHUB_ENV
              echo "LERNA_VERSION_QUERY=lerna version --yes --conventional-prerelease --preid ${{ inputs.tag }} --dry-run" >> $GITHUB_ENV
          elif ${{inputs.dryrun == true}}
          then
              echo "LERNA_VERSION_TYPE=ðŸ§ª Dry-Run" >> $GITHUB_ENV
              echo "LERNA_VERSION_QUERY=lerna version --yes --dry-run" >> $GITHUB_ENV
          elif ${{inputs.tag == 'alpha' || inputs.tag == 'beta' || inputs.tag == 'next'}}
          then
              echo "LERNA_VERSION_TYPE=ðŸš€ Prod Version w/Prerelease" >> $GITHUB_ENV
              echo "LERNA_VERSION_QUERY=lerna version --yes --conventional-prerelease --preid ${{ inputs.tag }}" >> $GITHUB_ENV
          else
              echo "LERNA_VERSION_TYPE=ðŸš€ Prod Version" >> $GITHUB_ENV
              echo "LERNA_VERSION_QUERY=lerna version --yes" >> $GITHUB_ENV
          fi

      - name: Final version type â†’ ${{ env.LERNA_VERSION_TYPE }}
        shell: bash
        run: echo "${{ env.LERNA_VERSION_QUERY }}"

      - name: Lerna Version ðŸ·ï¸
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          pnpm exec ${{ env.LERNA_VERSION_QUERY }}

      - name: Lerna Publish (build query)
        shell: bash
        run: |
          if ${{inputs.dryrun == true && (inputs.tag == 'alpha' || inputs.tag == 'beta' || inputs.tag == 'next')}}
          then
            echo "LERNA_PUBLISH_TYPE=ðŸ§ª Dry-Run w/Prerelease" >> $GITHUB_ENV
            echo "LERNA_PUBLISH_QUERY=lerna publish from-package --force-publish --yes --pre-dist-tag ${{ inputs.tag }} --dry-run" >> $GITHUB_ENV
          elif ${{inputs.dryrun == true}}
          then
            echo "LERNA_PUBLISH_TYPE=ðŸ§ª Dry-Run" >> $GITHUB_ENV
            echo "LERNA_PUBLISH_QUERY=lerna publish from-package --force-publish --yes --dist-tag latest --dry-run" >> $GITHUB_ENV
          elif [[ "${{ inputs.tag }}" == "alpha" || "${{ inputs.tag }}" == "beta" || "${{ inputs.tag }}" == "next" ]]
          then
            echo "LERNA_PUBLISH_TYPE=ðŸ“¦ Publish w/Prerelease" >> $GITHUB_ENV
            echo "LERNA_PUBLISH_QUERY=lerna publish from-package --force-publish --yes --pre-dist-tag ${{ inputs.tag }}" >> $GITHUB_ENV
          else
            echo "LERNA_PUBLISH_TYPE=ðŸ“¦ Publish Latest" >> $GITHUB_ENV
            echo "LERNA_PUBLISH_QUERY=lerna publish from-package --force-publish --yes --dist-tag latest" >> $GITHUB_ENV
          fi

      - name: Final publish type â†’ ${{ env.LERNA_PUBLISH_TYPE }}
        shell: bash
        run: echo "${{ env.LERNA_PUBLISH_QUERY }}"

      - name: Lerna Publish ðŸ“¦
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        id: lerna-publish
        run: pnpm exec ${{ env.LERNA_PUBLISH_QUERY }}

      - name: Website Dev Build
        run: pnpm build:dev

      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website
